GET http://localhost:4004/odata/v4/MyService/trainers

###POST

POST http://localhost:4004/odata/v4/MyService/trainers
Content-Type: application/json

{
    "name": "Ilyas",
      "locagtion": "Hyd",
      "designation": "MAN"
}

###Get from hana database

GET http://localhost:45041/odata/v4/MyService/trainers

###POST TO HANA DB

POST http://localhost:45041/odata/v4/MyService/trainers
Content-Type: application/json

{
    "name": "Fourth",
      "locagtion": "Hyd",
      "designation": "MAN"
}